[package]
name = "rust-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_engine = { version = "2.6.0", features=["event", "form"]}
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
